#!/bin/sh

export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get install -y --no-install-recommends git jq libssl-dev pkg-config

TOOLS="$(cat <<EOF | tr '\n' ' '
cargo-audit
cargo-cache
cargo-expand
cargo-license
cargo-update
grcov
EOF
)"

for TOOL in $TOOLS
do
  cargo install $TOOL
done

RUST_ANALYZER_LATEST=https://api.github.com/repos/rust-analyzer/rust-analyzer/releases/latest
RUST_ANALYZER_TAG="$(curl -fsSL $RUST_ANALYZER_LATEST | jq -r .tag_name)"
RUST_ANALYZER_SRC=$(mktemp -d)
git clone --depth=1 --branch="$RUST_ANALYZER_TAG" \
  https://github.com/rust-analyzer/rust-analyzer.git $RUST_ANALYZER_SRC
(cd $RUST_ANALYZER_SRC; cargo xtask install --server)

rm -rf $RUST_ANALYZER_SRC
apt-get clean
rm -rf /var/lib/apt/lists/*
rm -rf /var/tmp/*
rm -rf /tmp/*
