name: Build

on:
  schedule:
    - cron: '16 16 * * 5'  # Fri, 16:16 (UTC)
  repository_dispatch:
    types:
      - build

env:
  IMAGE: masnagam/rust-tools

jobs:
  build:
    strategy:
      matrix:
        distro:
          - debian
        include:
          - distro: debian
            platforms: >-
              linux/386,
              linux/amd64,
              linux/arm/v7,
              linux/arm64/v8,
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup QEMU user-mode emulation
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: ${{ matrix.platforms }}
          tags: ${{ env.IMAGE }}:${{ matrix.distro }}
          push: true
      - name: Test
        run: |
          # Enable experimental CLI features in Docker daemon
          echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart

          for platform in $(echo ${{ matrix.platforms }} | tr ',' ' ')
          do
            echo "Testing for $platform..."
            ./get-rust-tools --platform=$platform ${{ env.IMAGE }}:${{ matrix.distro }} | tar -tvz
          done
