name: Build

on:
  schedule:
    - cron: '16 16 * * 5'  # Fri, 16:16 (UTC)
  repository_dispatch:
    types:
      - build

env:
  IMAGE: masnagam/rust-tools
  PLATFORMS: linux/386,linux/amd64,linux/arm/v7,linux/arm64
  CARGO_BUILD_JOBS: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ env.IMAGE }}:latest
          push: true
      - name: Test
        run: |
          # Enable experimental CLI features in Docker daemon
          echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart

          for platform in $(echo '${{ env.PLATFORMS }}' | tr ',' ' ')
          do
            echo "Testing for $platform..."
            ./get-rust-tools --platform $platform | tar -tvz
          done
